name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled files go
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  my_new_project:
    +materialized: view         # Default for all models in this project

    staging:
      +materialized: view       # Keep staging models as views

    marts:
      core:
        +materialized: table    # Tables for facts and dimensions
