name: 'dbt_pro'
version: '1.0.0'

profile: 'dbt_pro'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"


models:
  dbt-snowflake-credit-card-analytics:
    +generate_schema_name: generate_schema_name  # call your macro

    staging:
      +materialized: view

    marts:
     core:
      +materialized: table
